#!/bin/bash -l
#SBATCH -A g2020008             # code of the project
#SBATCH -p core                 # core/ node
#SBATCH -n 8                   # nr of cores/ nodes
#SBATCH -t 01:10:00             # time needed (dd-hh:mm:ss)
#SBATCH -J tophat_scaffold6     # a name for your job
#SBATCH --mail-type=ALL         #required
#SBATCH --mail-user Satyakrishnaprasanna.Kolluri.2805@student.uu.se

#Load modules
module load bioinfo-tools
module load samtools
module load bowtie2
module load tophat

#code to run
for file in /home/satya/glob/5_Tean_Teh_2017/transcriptome/trimmed/*_06.1.fasta.gz
do
   file2="$(sed 's/_06\.1/_06.2\' <<<$file)"
   output=$(basename $file)
   tophat -o /home/satya/glob/tophat_scaf6_outfiles/tophat_out_${output%.fastq.gz} \
   -p 8 /home/satya/pilon/bowtie2/ $file $file2
done
 
